---
collections:
  - name: ansible.netcommon
  - name: ansible.utils
  - name: cisco.ios
  - name: cisco.nxos
  - name: lvrfrc87.git_acp
  - name: octupus.o4n_dev_git
  - name: octupus.o4n_azure_fileshare
  - name: awx.awx
  - name: ansible.posix
  - name: ansible.windows
  - name: community.general
  - name: manusl_networking.o4n_modules
  - name: check_point.mgmt
  - name: octupus.o4n_checkpoint
  - name: f5networks.f5_modules
  - name: octupus.o4n_f5
  - name: octupus.o4n_diff
  - name: community.windows

